### ISSUE TITLE
Download links issue

### ISSUE THREAD

**Issue by samadii** [musa-42/streamer_file#1]
Unable to download file. 
 error code: 29
 reason: The response status is not successful. status=503

**Comment by musa-42** [comment]
Send more information with the log

**Comment by samadii** [comment]
[file2linksobhi-logs-1620213353881.txt](https://github.com/musa-42/streamer_file/files/6426677/file2linksobhi-logs-1620213353881.txt)

**Comment by samadii** [comment]
For deploy, i created app.json in the fork and then used this link to deploy :
https://heroku.com/deploy?template=https://github.com/Soheib1378/streamer_file

**Comment by musa-42** [comment]
You must first clone the file, then modify the config files and enter the following commands to install
- install Heroku Cli 
- cd streamer_file
- heroku login
- heroku create
- heroku stack:set container
- git add .
- git commit -am "first deploy"
- git push heroku master
